local map = vim.keymap.set

map("n", "gR", "<cmd>Telescope lsp_references<CR>", { desc = "LSP: Show references" })
map("n", "gD", vim.lsp.buf.declaration, { desc = "LSP: Go to declaration" })
map("n", "gd", "<cmd>Telescope lsp_definitions<CR>", { desc = "LSP: Show definitions" })
map("n", "gi", "<cmd>Telescope lsp_implementations<CR>", { desc = "LSP: Show implementations" })
map("n", "gt", "<cmd>Telescope lsp_type_definitions<CR>", { desc = "LSP: Show type definitions" })
map({ "n", "v" }, "<leader>a", vim.lsp.buf.code_action, { desc = "LSP: Code actions" })
map("n", "<leader>rn", vim.lsp.buf.rename, { desc = "LSP: Rename symbol" })
map("n", "<leader>D", "<cmd>Telescope diagnostics bufnr=0<CR>", { desc = "LSP: Buffer diagnostics" })
map("n", "<leader>d", vim.diagnostic.open_float, { desc = "LSP: Diagnostic details" })
map("n", "[d", function()
   vim.diagnostic.jump({ count = -1, float = true })
end, { desc = "LSP: Previous diagnostic" })
map("n", "]d", function()
   vim.diagnostic.jump({ count = 1, float = true })
end, { desc = "LSP: Next diagnostic" })
map("n", "K", vim.lsp.buf.hover, { desc = "LSP: Hover documentation" })
map("n", "<leader>rs", "<cmd>LspRestart<CR>", { desc = "LSP: Restart server" })
map("n", "<leader>f", function()
   vim.lsp.buf.format({ async = true })
end, { desc = "LSP: Format buffer" })
map("n", "<leader>wa", vim.lsp.buf.add_workspace_folder, { desc = "LSP: Add workspace folder" })
map("n", "<leader>wr", vim.lsp.buf.remove_workspace_folder, { desc = "LSP: Remove workspace folder" })
map("n", "<leader>wl", function()
   print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
end, { desc = "LSP: List workspace folders" })
map("n", "<C-k>", vim.lsp.buf.signature_help, { desc = "LSP: Signature help" })
map("n", "<leader>q", vim.diagnostic.setloclist, { desc = "LSP: Diagnostics to location list" })
